#!/usr/bin/env python3
"""Generate per-type GEMV instance .cu files for parallel nvcc compilation.

Following llama.cpp's generate_cu_files.py pattern, each quantized type gets
its own .cu file containing an explicit template instantiation. This allows
nvcc to compile them in parallel, significantly reducing build time.

Usage:
    python tools/generate_gemv_instances.py
    # Generates: src/operators/cuda/gemv-instance-*.cu

To integrate with CMake, replace cuda_gemv_instances.cu with the generated
files in target_sources().
"""

import os

TYPES = ["q4_0", "q4_1", "q4_k", "q8_0", "q3_k", "q6_k"]

ENUM_MAP = {
    "q4_0": "Q4_0",
    "q4_1": "Q4_1",
    "q4_k": "Q4_K",
    "q8_0": "Q8_0",
    "q3_k": "Q3_K",
    "q6_k": "Q6_K",
}

INSTANCE_TEMPLATE = """// Auto-generated by tools/generate_gemv_instances.py — DO NOT EDIT
#include "cuda_gemv_tmpl.cuh"
#include "cuda_gemv.h"

namespace forge {{
namespace cuda {{

#define INST_GEMV(DT)                                                       \\
    template void launch_gemv_typed_transB<DT>(                             \\
        const float*, const void*, float*, int, int, cudaStream_t);         \\
    template void launch_gemv_typed_transB_batch<DT>(                       \\
        const float*, const void*, float*, int, int, int, cudaStream_t);

INST_GEMV(DataType::{enum_name})

#undef INST_GEMV

}}  // namespace cuda
}}  // namespace forge
"""

DISPATCH_TABLE = """// Auto-generated by tools/generate_gemv_instances.py — DO NOT EDIT
// This file provides the dispatch tables and must include ALL instance headers.
#include "cuda_gemv_tmpl.cuh"
#include "cuda_gemv.h"

namespace forge {{
namespace cuda {{

{instances}

const GemvFn gemv_dispatch[18] = {{
    /* FP32=0  */ nullptr,
    /* FP16=1  */ nullptr,
    /* Q4_0=2  */ launch_gemv_q4_0_transB,                          // special smem/splitK
    /* Q4_1=3  */ launch_gemv_typed_transB<DataType::Q4_1>,
    /* Q4_K=4  */ launch_gemv_typed_transB<DataType::Q4_K>,
    /* INT8=5  */ nullptr,
    /* INT32=6 */ nullptr,
    /* Q8_0=7  */ launch_gemv_typed_transB<DataType::Q8_0>,
    /* Q5_0=8  */ nullptr,
    /* Q5_1=9  */ nullptr,
    /* Q2_K=10 */ nullptr,
    /* Q3_K=11 */ launch_gemv_typed_transB<DataType::Q3_K>,
    /* Q5_K=12 */ nullptr,
    /* Q6_K=13 */ launch_gemv_typed_transB<DataType::Q6_K>,
    /* IQ2_S=14*/ nullptr,
    /* BF16=15 */ nullptr,
    /* IQ2_XXS=16 */ nullptr,
    /* IQ4_NL=17  */ nullptr,
}};

const GemvBatchFn gemv_batch_dispatch[18] = {{
    /* FP32=0  */ nullptr,
    /* FP16=1  */ nullptr,
    /* Q4_0=2  */ launch_gemv_typed_transB_batch<DataType::Q4_0>,
    /* Q4_1=3  */ launch_gemv_typed_transB_batch<DataType::Q4_1>,
    /* Q4_K=4  */ launch_gemv_typed_transB_batch<DataType::Q4_K>,
    /* INT8=5  */ nullptr,
    /* INT32=6 */ nullptr,
    /* Q8_0=7  */ launch_gemv_typed_transB_batch<DataType::Q8_0>,
    /* Q5_0=8  */ nullptr,
    /* Q5_1=9  */ nullptr,
    /* Q2_K=10 */ nullptr,
    /* Q3_K=11 */ launch_gemv_typed_transB_batch<DataType::Q3_K>,
    /* Q5_K=12 */ nullptr,
    /* Q6_K=13 */ launch_gemv_typed_transB_batch<DataType::Q6_K>,
    /* IQ2_S=14*/ nullptr,
    /* BF16=15 */ nullptr,
    /* IQ2_XXS=16 */ nullptr,
    /* IQ4_NL=17  */ nullptr,
}};

}}  // namespace cuda
}}  // namespace forge
"""


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    cuda_dir = os.path.join(script_dir, "src", "operators", "cuda")

    for t in TYPES:
        filename = f"gemv-instance-{t}.cu"
        filepath = os.path.join(cuda_dir, filename)
        content = INSTANCE_TEMPLATE.format(enum_name=ENUM_MAP[t])
        with open(filepath, "w") as f:
            f.write(content)
        print(f"Generated {filename}")

    # Generate dispatch table file (includes all instances)
    instances = "\n".join(
        f'// Instance provided by gemv-instance-{t}.cu' for t in TYPES
    )
    dispatch_path = os.path.join(cuda_dir, "cuda_gemv_dispatch.cu")
    with open(dispatch_path, "w") as f:
        f.write(DISPATCH_TABLE.format(instances=instances))
    print("Generated cuda_gemv_dispatch.cu")


if __name__ == "__main__":
    main()
